# Generated by Django 6.0.7 on 2026-07-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('UG', 'Uganda'), ('KE', 'Kenya'), ('TZ', 'Tanzania'), ('NG', 'Nigeria'), ('GH', 'Ghana'), ('OTHER', 'Other')], max_length=10)),
                ('method_name', models.CharField(help_text='e.g. MTN Mobile Money, M-Pesa, Airtel Money', max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=150)),
                ('account_number', models.CharField(help_text='Till number, paybill, phone number, etc.', max_length=100)),
                ('instructions', models.TextField(help_text='Step by step guide shown to the user, e.g. Go to M-Pesa > Lipa na M-Pesa > ...')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['country', 'display_order'],
            },
        ),
    ]
