# Generated by Django 6.0.6 on 2026-07-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='payment_link',
            field=models.URLField(blank=True, help_text='External payment link for Eversend or similar'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='required_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum amount required to auto-activate the account', max_digits=10),
        ),
    ]
