# Generated by Django 6.0.6 on 2026-07-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmethod_payment_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='kenya', max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('business_shortcode', models.CharField(blank=True, help_text='Safaricom till number or shortcode', max_length=20)),
                ('consumer_key', models.CharField(blank=True, max_length=255)),
                ('consumer_secret', models.CharField(blank=True, max_length=255)),
                ('passkey', models.CharField(blank=True, max_length=500)),
                ('callback_url', models.URLField(blank=True, help_text='Your callback URL for M-Pesa')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('instructions', models.TextField(blank=True, help_text='Display instructions for the user')),
                ('required_amount', models.DecimalField(decimal_places=2, default=550, help_text='Amount required for activation', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'M-Pesa configuration',
                'verbose_name_plural': 'M-Pesa configurations',
            },
        ),
    ]
