# Generated by Django 6.0.7 on 2026-07-15 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('nationality', models.CharField(choices=[('UG', 'Uganda'), ('KE', 'Kenya'), ('TZ', 'Tanzania'), ('NG', 'Nigeria'), ('GH', 'Ghana'), ('OTHER', 'Other'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='provider_photos/')),
                ('chat_rate', models.DecimalField(decimal_places=2, help_text='Flat fee in USD to start a chat with this provider', max_digits=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Provider can be hidden from listings without deleting')),
                ('id_document', models.ImageField(blank=True, help_text='ID document for admin verification, not shown publicly', null=True, upload_to='provider_verification/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
