# Generated by Django 6.0.6 on 2026-07-15 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='payments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='transaction_code',
            field=models.CharField(blank=True, help_text='Additional transaction/reference code from the payment proof', max_length=100),
        ),
    ]
