# Generated by Django 6.0.6 on 2026-07-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_deposit_payment_method_deposit_transaction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deposit',
            name='mpesa_request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
